name: Release

on:
  push:
    branches:
      - master
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          bump_each_commit: true
          search_commit_body: true

      - name: created tag
        run: |
          echo "${{ steps.version.outputs.version }}"
          echo "${{ steps.version.outputs.version_tag }}"

