name: Release

on:
  push:
    branches:
      - master
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x

      - id: version
        uses: gittools/actions/gitversion/execute@v0

      - name: created tag
        run: |
          echo "${{ steps.version.outputs.semVer }}"
          echo "${{ steps.version.outputs.fullSemVer }}"

