name: Release

on:
  push:
    branches:
      - master
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: semver-tag
        uses: gandarez/semver-action@latest
      - name: created tag
        run: echo "${{ steps.semver-tag.outputs.semver_tag }}"

